### PR TITLE
Autovote System

### PR DESCRIPTION
**Pull request by ghost**
:cl:
- add: Added auto vote system

### CODE REVIEW

**Comment by sleepyyapril** [comment]
Nice

**Review by Memeji — APPROVED** [review]

**Review by ShadesMars — CHANGES_REQUESTED** [review]
Changes was requested on EE and now is not here, you should update it here too before merging: https://github.com/Simple-Station/Einstein-Engines/pull/1213

**Comment by fenndragon** [comment]
> Changes was requested on EE and now is not here, you should update it here too before merging: [Simple-Station/Einstein-Engines#1213](https://github.com/Simple-Station/Einstein-Engines/pull/1213)

Please specify the changes or suggest them directly

**Comment by Fansana** [comment]
> Changes was requested on EE and now is not here, you should update it here too before merging: [Simple-Station/Einstein-Engines#1213](https://github.com/Simple-Station/Einstein-Engines/pull/1213)

Sorry, no, I will do the changes when they come in. For now this is good enough.

**Pull request merged**
