### PR TITLE
Whitelist window

### PR DESCRIPTION
**Pull request by Skyedra**
This patch released under MIT, so if any other server wants to take and adapt for their own purposes, feel free!

### CODE REVIEW

**Comment by Skyedra** [comment]
Oh, oops, just realized it doesn't wordwrap if the whitelist message is wrong, will fix

**Comment by Skyedra** [comment]
Ok, fixed the wordwrap ^.^

**Comment by FoxxoTrystan** [comment]
Next time please fill out the description so its would be easier to understand what its does.

Also from looking its just add a whitelist window while also adding a new category to advertize others servers?

**Comment by Skyedra** [comment]
Check with floofmin or dm me on discord :)

**Pull request merged**
