### PR TITLE
Loin Cloth

### PR DESCRIPTION
**Pull request by ShadesMars**
# Description

Add the LoinCloth, a permit that replace your jumpsuit slot, making you able to wear your PDA, pocket ect... like wearing a normal jumpsuit.

Seem important in an 18+ server so there its is! in loadout or clothmate vendors!

<details><summary><h1>Media</h1></summary>
<p>

image

</p>
</details>

---

# Changelog

:cl:
- add: Add the LoinCloth.

### CODE REVIEW

**Comment by Fansana** [comment]
I dunno nudity permit sounds like a bad name for this. couldn't it be something like a loin strap? Still able to hold PDA and pockets?

**Comment by FoxxoTrystan** [comment]
> I dunno nudity permit sounds like a bad name for this. couldn't it be something like a loin strap? Still able to hold PDA and pockets?

Its named the "public nudity permit" with this description; "This permit entitles the bearer to conduct their duties without a uniform. Normally issued to furred crewmembers or those with nothing to hide."

I have seen this permit used in many SS13 18+

But if its need to be changed, the name that is possible, just suggest!

**Comment by Fansana** [comment]
I just think it makes no sense to wear a permit. A loin cloth makes much more sense, doesn't have have to render anything on the sprite.

**Comment by FoxxoTrystan** [comment]
> I just think it makes no sense to wear a permit. A loin cloth makes much more sense, doesn't have have to render anything on the sprite.

Alright then il make the changes.
A sprite change for the icon of the item and name/description.

**Comment by Fansana** [comment]
This is great.

**Comment by FoxxoTrystan** [comment]
bap

**Comment by Fansana** [comment]
test

**Comment by FoxxoTrystan** [comment]
Floofs

**Comment by Mnemotechnician** [comment]
Did you test if harpies can wear it? Since it lacks the jumpskirt tag.

**Comment by FoxxoTrystan** [comment]
> Did you test if harpies can wear it? Since it lacks the jumpskirt tag.

They dont because there is no sprite, only icon sprite.
its an "go nude" clothing.

**Pull request merged**
